18:40:55:ERROR [logger_base.py:15] Mensaje a nivel error)]
18:40:55:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:02:32:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:02:32:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:02:59:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:02:59:INFO [logger_base.py:13] Mensaje a nivel info)]
19:02:59:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:02:59:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:02:59:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:05:25:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:05:25:INFO [logger_base.py:13] Mensaje a nivel info)]
19:05:25:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:05:25:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:05:25:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:05:25:DEBUG [Persona.py:55] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:06:25:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:06:25:INFO [logger_base.py:13] Mensaje a nivel info)]
19:06:25:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:06:25:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:06:25:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:06:25:DEBUG [Persona.py:55] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:07:18:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:07:18:INFO [logger_base.py:13] Mensaje a nivel info)]
19:07:18:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:07:18:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:07:18:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:07:18:DEBUG [Persona.py:55] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:08:54:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:08:54:INFO [logger_base.py:13] Mensaje a nivel info)]
19:08:54:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:08:54:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:08:54:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:08:54:DEBUG [Persona.py:55] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:08:54:DEBUG [Persona.py:57] 
        id_persona: None
        nombre: Jose
        apellido: Lopez
        email: ljose@gmail.com
        )]
19:30:01:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:30:01:INFO [logger_base.py:13] Mensaje a nivel info)]
19:30:01:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:30:01:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:30:01:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:30:01:DEBUG [Persona.py:57] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:30:01:DEBUG [Persona.py:61] 
        id_persona: None
        nombre: Jose
        apellido: Lopez
        email: ljose@gmail.com
        )]
19:30:09:DEBUG [logger_base.py:12] Mensaje a nivel debug)]
19:30:09:INFO [logger_base.py:13] Mensaje a nivel info)]
19:30:09:WARNING [logger_base.py:14] Mensaje a nivel warning)]
19:30:09:ERROR [logger_base.py:15] Mensaje a nivel error)]
19:30:09:CRITICAL [logger_base.py:16] Mensaje a nivel critical)]
19:30:09:DEBUG [Persona.py:57] 
        id_persona: 1
        nombre: Juan
        apellido: Perez
        email: jperez@gmail.com
        )]
19:30:09:DEBUG [Persona.py:61] 
        id_persona: None
        nombre: Jose
        apellido: Lopez
        email: ljose@gmail.com
        )]
19:30:09:DEBUG [Persona.py:63] 
        id_persona: 1
        nombre: None
        apellido: None
        email: None
        )]
21:56:12:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
21:56:12:INFO [logger_base.py:28] Mensaje a nivel info)]
21:56:12:WARNING [logger_base.py:29] Mensaje a nivel warning)]
21:56:12:ERROR [logger_base.py:30] Mensaje a nivel error)]
21:56:12:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
21:56:12:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x000001D3D7E10E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
21:57:22:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
21:57:22:INFO [logger_base.py:28] Mensaje a nivel info)]
21:57:22:WARNING [logger_base.py:29] Mensaje a nivel warning)]
21:57:22:ERROR [logger_base.py:30] Mensaje a nivel error)]
21:57:22:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
21:57:22:ERROR [Conexion.py:35] Error conectando conexion: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte)]
22:00:31:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:00:31:INFO [logger_base.py:28] Mensaje a nivel info)]
22:00:31:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:00:31:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:00:31:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:00:31:ERROR [Conexion.py:35] Error conectando conexion: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte)]
22:10:56:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:10:56:INFO [logger_base.py:28] Mensaje a nivel info)]
22:10:56:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:10:56:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:10:56:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:10:56:ERROR [Conexion.py:35] Error conectando conexion: 'utf-8' codec can't decode byte 0xf3 in position 85: invalid continuation byte)]
22:11:05:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:11:05:INFO [logger_base.py:28] Mensaje a nivel info)]
22:11:05:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:11:05:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:11:05:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:11:05:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x000001A637F40E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:11:46:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:11:46:INFO [logger_base.py:28] Mensaje a nivel info)]
22:11:46:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:11:46:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:11:46:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:11:46:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x0000023631520E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:11:58:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:11:58:INFO [logger_base.py:28] Mensaje a nivel info)]
22:11:58:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:11:58:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:11:58:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:11:58:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x000001BB1E620E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:12:17:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:12:17:INFO [logger_base.py:28] Mensaje a nivel info)]
22:12:17:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:12:17:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:12:17:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:12:17:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x000001D9F22A0E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:13:16:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:13:16:INFO [logger_base.py:28] Mensaje a nivel info)]
22:13:16:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:13:16:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:13:16:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:13:16:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x00000270941F0E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:14:46:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:14:46:INFO [logger_base.py:28] Mensaje a nivel info)]
22:14:46:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:14:46:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:14:46:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:14:46:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x0000029AFE930E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
22:17:50:DEBUG [logger_base.py:27] Mensaje a nivel debug)]
22:17:50:INFO [logger_base.py:28] Mensaje a nivel info)]
22:17:50:WARNING [logger_base.py:29] Mensaje a nivel warning)]
22:17:50:ERROR [logger_base.py:30] Mensaje a nivel error)]
22:17:50:CRITICAL [logger_base.py:31] Mensaje a nivel critical)]
22:17:50:DEBUG [Conexion.py:31] Conexion establecida<connection object at 0x0000025B96290E10; dsn: 'user=postgres password=xxx dbname=test_bd host=localhost port=5432', closed: 0>)]
